config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :teachers
  root "teachers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	belongs_to :user
	validates :name, presence: true
	validates :age, presence: true
	validates :experience, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :teachers 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :authenticate_user!

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :age, :class)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	def index
		@teachers = Teacher.all
	end
	def show
		@teacher = Teacher.find(params[:id])
	end
	def new
		@teacher = Teacher.new
	end
	def create
		@teacher = current_user.teachers.new(teacher_params)
		if @teacher.save
			redirect_to @teacher
		else
			render 'new'
		end
	end
	def edit
		@teacher = Teacher.find(params[:id])
	end
	def update
		@teacher = Teacher.find(params[:id])
		if @teacher.update(teacher_params)
			redirect_to @teacher
		else
			render 'edit'
		end

	end
	def destroy
		@teacher = Teacher.find(params[:id])
		if @teacher.destroy
			redirect_to @teacher
		end
	end


end
private

	def teacher_params
		params.require(:teacher).permit(:name,:age,:experience)
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :class %>
    <%= form.number_field :class %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%= student.class %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Class:</strong>
  <%= @student.class %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/teachers/edit.html.erb
<h1>Editing the Teacher</h1>
<%= form_for @teacher do |f| %>
  <%= f.label :name %> : <%= f.text_field :name %><br />

  <%= f.label :age %> : <%= f.text_field :age %><br />

  <%= f.label :experience %> : <%= f.text_field :experience %><br />

  <%= f.submit %>
<% end %>

app/views/teachers/index.html.erb
<h1>Listing Teachers</h1>
 
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Experince</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.age %></td>
        <td><%= teacher.experience %></td>
        <td><%= link_to "show", teacher %></td>
        <td><%= link_to "edit", edit_teacher_path(teacher) %></td>
        <td><%= link_to "delete",teacher,method: :delete, data:{confirm: "are you sure?"} %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>

<%= link_to "New Teacher", new_teacher_url %>

app/views/teachers/new.html.erb
<%= form_for @teacher do |f| %>
<% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :age %>:
  <%= f.text_field :age %><br />

  <%= f.label :experience %>:
  <%= f.text_field :experience %><br />

  <%= f.submit %>

<% end %><br><br>
<%=link_to "All Teachers",teachers_path%>

app/views/teachers/show.html.erb
<h1>Particular Teacher</h1>
<strong>NAME</strong> = <%= @teacher.name %><br>
<strong>AGE</strong> = <%= @teacher.age %><br>
<strong>EXPERIENCE</strong> = <%= @teacher.experience %><br><br>
<%= link_to "Total teachers",teachers_path %>